### PR TITLE
Various improvements and fixes

### PR DESCRIPTION
**Pull request by sukidog**
See commits

### CODE REVIEW

**Comment by sukidog** [comment]
Liviu, should I have made the pull request into your 'develop' branch instead of 'pyocd-dev'?

**Comment by ilg-ul** [comment]
for the moment please keep the changes in the pyocd-dev.

**Comment by ilg-ul** [comment]
I merged the changes. I also silenced warnings and reformatted the source code (please be sure you always reformat before committing).

the json parser seems a little outdated, it triggers lots of warnings.

regarding the look of the Debugger tab, please further collapse the 4 buttons (Halt at hard fault + Step into, Enable semihosting + Use GDB syscalls).

**Comment by flit** [comment]
Thanks for merging. We'll rearrange the UI as requested, just haven't gotten to it yet.

Regarding the JSON parser, I chose that one because it's relatively small and simple compared to others I found at the time. But there certainly may be better ones available.

**Comment by sukidog** [comment]
I fixed all warnings in the plug-in several days ago. I have it on a branch to be committed later

John

**Comment by ilg-ul** [comment]
I silenced them too, please check the develop branch.

**Comment by ilg-ul** [comment]
>  We'll rearrange the UI

please take a look at the J-Link UI, there too some options are grouped on the same line, and right aligned.

**Comment by sukidog** [comment]
I'll take care of this tomorrow

John

**Comment by sukidog** [comment]
Well, we took very different approaches. You silenced the warnings, whereas
I fixed the the code (made the code more type-safe). I'll make a pull
request tomorrow with my changes.

**Comment by ilg-ul** [comment]
Ok, sure, go ahead, the only problem with this approach is if you'll be willing to do it each time the author will release a new version.

**Comment by sukidog** [comment]
Well, the last commit by the author on github was 19 months ago. I'm
thinking there won't be an update any time soon (if ever). I rather have
the code type-safe in case we want to tweak/improve it. And if I'm wrong
and there is an update and we move to it, yep, I'll fix the warnings again.
It took but about five minutes.

**Comment by ilg-ul** [comment]
In my future plug-ins I'll use JSON intensively, so we'll most probably include JSON support in the core plug-in.

**Comment by sukidog** [comment]
And I assume that won't be the one in the pyOCD plugin. In that case, not
much point pushing changes that fix the type-safety issues. I'll update the
pyOCD plugin to use whatever you end up putting in core

**Comment by ilg-ul** [comment]
> won't be the one in the pyOCD plugin

a quick search revealed a reference api, from oracle: https://jsonp.java.net

any comments on that?

**Comment by sukidog** [comment]
Java 7 has a (this) JSON parser. But since the goal, I believe, is to
maintain compatibility with 1.6, we can't use it.

**Comment by sukidog** [comment]
Liviu, regarding "please be sure you always reformat before committing", the JDT formatting behavior is highly customizable and that customization is not in git. Getting individual developers to run the formatter locally before committing is asking for trouble. If you want consistency in the code (which, I this is great, btw), the best way to do that is via a git hook. Barring that, a single person who handles the pull requests can apply his formatting (that would be you :-)

**Comment by ilg-ul** [comment]
I checked and 1.7 is required since Eclipse Luna (CDT 8.4), and 1.8 will be required for CDT 8.9 (Mars.2). we'll probably raise the limit to 1.7 starting with v3.x of the plug-ins, planned for Q2, which might be also the time for Eclipse 4.6.

**Comment by sukidog** [comment]
Excellent. I'm all for moving forward. Our product uses 1.7.

**Comment by ilg-ul** [comment]
> JDT formatting behavior is highly customizable and that customization is not in git

now it is. I enable 'per project' formatter settings, and this should override any workspace formatting you use.

personally I'm not interested in any formatting details and customisations, Eclipse built-in format is fine for me, I'm more interested in a consistent look.

> a git hook

yes, that would be the absolute consistency, but it just adds some more complexity to the setup, which I'm reluctant to accept.

**Comment by sukidog** [comment]
In my experience and opinion, the default JDT formatter settings can
generate quite an eyesore. But, obviously, this is your call. Anyway, I'll
run the formatter now that the settings are in git.

**Comment by sukidog** [comment]
I have your project settings changes. I picked a number of files at random
and did a format. They all incurred changes. This is a problem. That means
that the current codebase does not currently conform to the formatting
options (settings) you committed. This means that if you expect us to for a
Format before committing a change for a pull request, you're going to get a
file that has functional changes mixed in with cosmetic ones. This will
make things difficult to determine what are the "real" changes looking at a
diff. This is what you want?

**Comment by ilg-ul** [comment]
this means you have some other custom settings in your environment, since my settings are default.

if you can't provide standard formatting, I'll reformat everything anyway.

the last commit formatted only 2 files.

**Comment by sukidog** [comment]
I assure you I did not adjust any global preferences related to Java
formatting. As I said, relying on developers to format code is just fraught
with problems. The only reliable approach is SCM hooks. I'll just leave it
to you to format as you wish.

**Comment by ilg-ul** [comment]
I did the following test: 

- unpacked eclipse-rcp-mars-1-macosx-cocoa-x86_64.tar.gz, 
- created a new workspace
- imported the pyocd plug-in, without copying
- selected src
- clicked source -> format

according to git, nothing changed.

if a similar test from your side triggers changes, then you are right, relying on developers using different platforms to format code is not reliable. otherwise you have custom settings.

**Comment by sukidog** [comment]
Problem is that you're assuming contributors are all using the same Eclipse
you are, or that the default formatting behavior doesn't change from one
Eclipse version to another. So, yes, using Mars, there is no change when I
format the pyocd src folder. But there are a lot of changes when I do the
same in Luna. And I'm using Luna for develolpment.

BTW, I used fresh/new installations of Luna and Mars to verify this.

**Comment by ilg-ul** [comment]
> there are a lot of changes when I do the same in Luna.

now that we know it, we'll avoid using Luna formatter. probably with each version the format will slightly change.

**Pull request merged**
