### PR TITLE
pyOCD launch config plugin

### PR DESCRIPTION
**Pull request by flit**
Implements a launch config plugin for the [pyOCD](https://github.com/mbedmicro/pyOCD) gdb server.

### CODE REVIEW

**Comment by ilg-ul** [comment]
Hi Chris, thank you for your contribution, the merge seems ok.

However, please consider the following suggestions:

- brace all trace messages with `if (Activator.getInstance().isDebugging())`, similar to the code in the J-Link plug-in
- reorganise a bit the layout of the Debugger tab, to make it more compact; 
  - try to bring the _Enable semihosting_ and _Use GDB syscalls for semihosting_ on a single line before the _Semihosting port_;
  - try to group _Halt at hard fault_ and _Step into interrupts_ on a single line

**Comment by ilg-ul** [comment]
And please edit the source file headers and add you name to the Contributors.

**Comment by ilg-ul** [comment]
The pyOCD plug-in should be now available for testing from updates-test.

**Comment by ilg-ul** [comment]
We tried to instal it on an system using Java 7, the plug-in did not complain, but when trying to start it, it failed with a missing dependency.

Please be sure you stick with Java 7 for the moment, probably from CDT 9 we'll upgrade to 8.

**Comment by ilg-ul** [comment]
I created a new branch (pyocd-dev), please use it for your development until ready for prime time.

**Comment by flit** [comment]
Hi Liviu, thanks for reviewing so quickly! I'll make all requests changes.

Regarding the UI layout, I was trying to keep all options in one vertical line so it's easier to scan visually. But I'll make the requested changes.

(It may take a few weeks to get everything done and create a new PR due to other projects.)

**Comment by ilg-ul** [comment]
> edit the source file headers and add you name to the Contributors.

this obviously refers to files that you changed.

**Comment by ilg-ul** [comment]
> UI layout

due to a poor swt implementation on mac, the inner scrollbars are too thin and hide too quickly, so it is quite difficult to scroll inner windows; better keep the height as low as possible.

> updates-test

since I had to issue a maintenance release to fix a bug, updates-test no longer includes your plug-in.

I'll add it when you're ready.

**Comment by flit** [comment]
Yes, I've noticed the scrolling issue, but I wasn't sure what was causing it. I guess I'm used to a large screen.

No worries about updates-test.

**Comment by ilg-ul** [comment]
> Please be sure you stick with Java 7 for the moment

I just noticed the existing GNU ARM Eclipse code to explicitly refer to 1.6; I don't know what to say, if you can make it work with 1.6 it would be even better.

**Comment by flit** [comment]
Ok, I'll definitely try. Thanks for pointing that out. The only reason I ended up using Java 8 features is because I'm not very familiar with modern Java development.

-c

**Pull request merged**
