### PR TITLE
Fix incorrect Activator class specification. Probably a refactoring artifact

### PR DESCRIPTION
**Pull request by sukidog**

### CODE REVIEW

**Comment by ilg-ul** [comment]
I confirm the s/ad/aducm36x/ change, but I do not see any problem with the line-ending. what's wrong with them?

**Comment by sukidog** [comment]
Nothing. It was a goof on my end. I accidentally changes the line endings locally and did not realize until after the commit (and it did not occur to me to make the second commit an --amend)

**Comment by ilg-ul** [comment]
then I'm reluctant to apply the complete patch.

could you close the pull request and resubmit a correct one?

**Comment by sukidog** [comment]
you bet

**Pull request closed without merging**
