### PR TITLE
Fix issue #102. Do not prevent user from relying on gdbserver in PATH…

### PR DESCRIPTION
**Pull request by sukidog**
… and specifying exe as simple name

### CODE REVIEW

**Comment by ilg-ul** [comment]
ah, so this is the problem...

@flit, could you change the logic behind the executable field, to match the logic existing in the openocd & j-link plug-ins? I guess there are no such validations there.

if you know of other places where you introduced behaviour changes, we should discuss if the other plug-ins need adjustments, but the behaviour should be consistent between all debugging plug-ins.

**Comment by sukidog** [comment]
I can't tell if you're asking me to change the behavior in the pyocd plugin to be like the others or the other way around

John

**Comment by ilg-ul** [comment]
no, I'm asking Chris Reed @flit, he's the author of the pyocd plug-in, and I think he is in the best position to find a solution.

**Comment by flit** [comment]
Can you describe the current behaviour? It looked pretty simple to me. I didn't add or remove any logic related to that field when I originally created the plugin.

@sukidog improved the plugin by reporting to the user if the executable could not be found. This is important, because the plugin UI runs the pyOCD executable in order to populate the board and target fields.

Btw, for all intents and purposes, @sukidog is co-owner of the plugin. He can make decisions about the plugin.

**Comment by sukidog** [comment]
We've had this discussion before. Chris and I co-own this plugin and I will probably be the primary maintainer of it. 

John

**Comment by flit** [comment]
But in general, yes I completely agree that behaviour should be the same for all the debugging plugins.

**Comment by ilg-ul** [comment]
> @sukidog improved the plugin

sorry, the copyright notice refers to "Chris Reed" and "John Cortell"; you're obviously free to use any alias you like, but since there is no reference to your real names, you should assume some misunderstandings.

---

otherwise, regarding the plug-in behaviour, if I got it right, the point is not to simply validate the field (which the other plug-ins do not), but to call the program to get some additional data to populate the other fields. and the suggested patch fixes this problem. can you confirm this?

**Comment by sukidog** [comment]
The plugin has been calling pyocd's gdbserver all along to get the list of
plugged-in boards. The only thing this pull request does is make it
*possible* for that logic to work when the user has pyOCD in PATH and he
has specified the gdbserver by simple name (sans path). BTW, this is not a
hypothetical scenario. This deficiency was found and reported to me by a
user.

**Comment by ilg-ul** [comment]
please check 2.12.1-201603192008 from updates-test.

**Comment by ilg-ul** [comment]
fixed in 2.12.1-201604190915

**Pull request merged**
