### PR TITLE
Fix remaining warnings in pyOCD plugin

### PR DESCRIPTION
**Pull request by sukidog**

### CODE REVIEW

**Comment by sukidog** [comment]
BTW, the pull request name didn't reflect it, but this also has a compacting of the checkboxes

**Comment by ilg-ul** [comment]
I merged the changes, the buttons are now on the same line.

the first ones, that come after the ports, are too close. if you do not like right aligning them, as I did for j-link, at least make the space larger. probably a better look would be obtained if you simply make two cells of 50% width.

**Comment by sukidog** [comment]
They're not on the same line for me. And there's a nice gap between the two columns. 

image

**Comment by sukidog** [comment]
Ah, you're talking about a different set of checkboxes now. OK. I'll adjust those. I don't like right-aligned, but I'll add some padding

**Comment by ilg-ul** [comment]
as I said, split the row in 2 halves.

**Comment by sukidog** [comment]
Will this work for you? 
image

**Comment by ilg-ul** [comment]
I would say it looks better. if you make the window wider, does the ration remain 50%?

if so, use the same recipe for the other buttons (Fast sector compare, Step into interrupts, Use GDB...)

Also make sure the Executable edit is aligned with the GDB port.

**Comment by sukidog** [comment]
It does, but I don't like it and will probably change it. UI that expands
inter-widget spacing simply because its parent expands is not desirable,
IMO. I.e., if I make the launch config 1500 pixels wide, I don't want to
see a sea of space between columns of checkboxes. That's just bad UI.
Widgets should be comfortably spaced away from each -- not too close, not
too far. Now, widgets with variable content (a text field with a path,
e.g)...there is does make sense to take your recommended approach.

I will fix the the Executable alignment, and I will add space between the
flash mode combobox and the checkbox

**Comment by ilg-ul** [comment]
regardless how you do it, it should be consistent across the window.

and be aware that absolute widths may lead to different renderings on GTK or Cocoa.

**Pull request merged**
