### PR TITLE
Update for CDT 9.0, part of Eclipse Neon

### PR DESCRIPTION
**Pull request by jonahkichwacoders**
Upgrade code to support API and other changes in CDT 9.0 / Eclipse Neon.

Note that Neon is due for release in about a month. After that point the URL for the p2 in the top pom.xml may want updating.

With this change, the minimum required version of CDT will be CDT 9.0 / Eclipse Neon. At the moment I don't expect this to be merged, but I wanted to share the exploratory work I had done somewhere.

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
This resolves Issue 116, at least if you ignore the supporting older versions of Eclipse issue.

**Comment by ilg-ul** [comment]
thank you, Jonah, I'll check this, but compatibility with older versions is mandatory.

we need a solution that does not refer to the deprecated classes, but also works with Mars and Luna.

**Comment by jonahkichwacoders** [comment]
Note that I don't have access to the setups required to tests some of the changes I have made here. Primarily this achieves building with newer CDT and Neon, sometimes there are semantic changes which need to be addressed too which will be visible on test.

**Comment by jonahkichwacoders** [comment]
> we need a solution that does not refer to the deprecated classes, but also works with Mars and Luna.

For that some more significant work will need to be done on refactoring away the differences. I may be able to look again at this, but only in a few weeks (after EclipseCon France where I am presenting [CDT: Latest & Greatest Tooling for C/C++](https://www.eclipsecon.org/france2016/session/cdt-latest-greatest-tooling-cc))

**Comment by ilg-ul** [comment]
I'll also take a look, but not sooner than 2 (maybe 3) weeks.

one thing is for sure, there will not be multiple separate code bases, I don't have the resources to manage the additional complexity.

**Comment by jonahkichwacoders** [comment]
My latest patch addresses some of the API changes. There is only one API change left to resolve, the change in GdbDebugServicesFactory constructor (See below). Once we resolve that it should be possible to change the target platform back to KeplerSR2 and then build for all versions from single source. Best suggestion I have at the moment is to copy GdbDebugServicesFactory from CDT.

(Marc Khouzam from https://bugs.eclipse.org/bugs/show_bug.cgi?id=488909#c3)
> To help anyone that has to adapt to this change, the modifications needed
> are simple:
> 
> 1- Any class extending GdbDebugServicesFactoryNS should no longer be needed.
> If such an extension contained changes in behavior, those changes should got
> into the corresponding extension of GdbDebugServicesFactory.
> 
> 2- Pass in the launch configuration to the constructor of
> GdbDebugServicesFactory

**Comment by jonahkichwacoders** [comment]
Abandoning this copy, new pull request against new develop-v3 branch coming

**Pull request closed without merging**
