### PR TITLE
#95: Added support for file protocol used in URL

### PR DESCRIPTION
**Pull request by marek-trmac**
#95: Added support for file protocol used in URL (fix for #95)

### CODE REVIEW

**Comment by ilg-ul** [comment]
it still does not work, it fails with PDSC size 0.

**Comment by marek-trmac** [comment]
If file exists, it works on my machine, Windows 7 64 bit. I've successfuly installed the package.

**Comment by ilg-ul** [comment]
the file exists, but `connection.getContentLength();` returns 0 for it :-(

I'll try to debug it and find a solution.

in my test I downloaded McuOnEclipse.Utility.pdsc and McuOnEclipse.Utility.1.0.0.pack from Erich's site.

it might be a url syntax problem, I don't know yet.

**Comment by ilg-ul** [comment]
it was a syntax problem in my config, now it is ok, I successfully installed the local package.

the current version is on updates-test.

**Comment by marek-trmac** [comment]
good news. same on my computer. thank you

**Comment by ilg-ul** [comment]
> it might be a url syntax problem, I don't know yet.

for the records: when I created the index file, I drag-and-dropped the path to the folder. since the path contains spaces, they were escaped with `\` resulting 

```
<pdsc url="file:///Users/ilg/My\ Files/MacBookPro\ Projects/GNU\ ARM\ Eclipse/Eclipse\ Workspaces/local-cmsis-repo" name="McuOnEclipse.Utility.pdsc"  version="1.0.0"/>
```
this proved not a good idea.

after removing the inner `\` chars, everything was fine.

so the correct syntax is:

```
<pdsc url="file:///Users/ilg/My Files/MacBookPro Projects/GNU ARM Eclipse/Eclipse Workspaces/local-cmsis-repo" name="McuOnEclipse.Utility.pdsc"  version="1.0.0"/>
```

**Comment by ilg-ul** [comment]
fixed in 2.12.1-201604190915

**Pull request merged**
