### PR TITLE
Update for CDT 9.0, part of Eclipse Neon

### PR DESCRIPTION
**Pull request by jonahkichwacoders**
Replacement for Pull 119

### CODE REVIEW

**Comment by jonahkichwacoders** [comment]
OK, this version of the pull request requires Neon RC3, but from a single source you should be able to run the plug-ins against CDT 8.x and CDT 9.x. 

If you would like help accessing the CDT for Neon RC3 plug-ins ahead of their general release in more than 1 week, so we have a chance of fixing anything, please let me know.

**Comment by ilg-ul** [comment]
in addition to your pull request, I added your name as contributor to the affected files, and increased some version numbers.

so far, so good, my test on Mars 2 passed.

the current release is available for testing from 

http://gnuarmeclipse.sourceforge.net/updates-test

> Neon RC3 ahead

yes, if you have an archive, or a test update site, I'll check on Neon too. I would also like to make it available to @mvrhov, who reported the problem.

**Comment by jonahkichwacoders** [comment]
I'll post a P2 site with the nightly build of CDT containing the changes, with any luck that will be later today.

**Comment by jonahkichwacoders** [comment]
Here is the P2 site with the build containing the changes to CDT: https://hudson.eclipse.org/cdt/job/cdt-9.0/lastSuccessfulBuild/artifact/releng/org.eclipse.cdt.repo/target/org.eclipse.cdt.repo.zip 

This will be in CDT RC3.

**Comment by ilg-ul** [comment]
we tested on a linux box, official Neon beta, install from your zip, install from updates-test, a qemu debug session, and everything was fine.

I guess we can consider this problem solved.

thank you,

Liviu

**Comment by jonahkichwacoders** [comment]
Hi Liviu,

I am very please to hear that!

Jonah

**Pull request merged**
