### PR TITLE
Fix warnings caused by unnecessary plugin.xml files and incorrectly set output specifier in build.properties

### PR DESCRIPTION
**Pull request by sukidog**
This removes about 20 of the 30-ish warnings in the code. I'll be making a few more pull requests for the remaining. Grouping them by the warning nature. These are no-brainers.

### CODE REVIEW

**Comment by ilg-ul** [comment]
I would prefer to keep the empty plugin.xml, could you update the patch to not remove them?

**Comment by sukidog** [comment]
Empty plugin.xmls restored. Keep in mind that this warning is not one PDE allows you to ignore via a project property.

**Comment by ilg-ul** [comment]
@sukidog, this pull request got a bit messy, please submit a clean one, just to fix the `output=` settings.

**Comment by sukidog** [comment]
Agreed.

**Pull request closed without merging**
